apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterscanbenchmarks.cis.cattle.io
spec:
  group: cis.cattle.io
  names:
    kind: ClusterScanBenchmark
    plural: clusterscanbenchmarks
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            clusterProvider:
              type: string
            customBenchmarkConfigMapName:
              type: string
            customBenchmarkConfigMapNameSpace:
              type: string
            maxKubernetesVersion:
              type: string
            minKubernetesVersion:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
