apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterscanreports.securityscan.cattle.io
spec:
  group: securityscan.cattle.io
  names:
    kind: ClusterScanReport
    plural: clusterscanreports
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            benchmarkVersion:
              type: string
            lastRunTimestamp:
              type: string
            reportJSON:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
