apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterscans.securityscan.cattle.io
spec:
  group: securityscan.cattle.io
  names:
    kind: ClusterScan
    plural: clusterscans
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            scanProfileName:
              type: string
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  lastUpdateTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              nullable: true
              type: array
            enabled:
              type: boolean
            lastRunTimestamp:
              type: string
            observedGeneration:
              type: integer
            summary:
              nullable: true
              properties:
                fail:
                  type: integer
                notApplicable:
                  type: integer
                pass:
                  type: integer
                skip:
                  type: integer
                total:
                  type: integer
              type: object
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
