apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterscanprofiles.securityscan.cattle.io
spec:
  group: securityscan.cattle.io
  names:
    kind: ClusterScanProfile
    plural: clusterscanprofiles
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            benchmarkVersion:
              type: string
            clusterProvider:
              type: string
            configMap:
              type: string
            configMapNamespace:
              type: string
            maxKubernetesVersion:
              type: string
            minKubernetesVersion:
              type: string
            skipTests:
              items:
                type: string
              nullable: true
              type: array
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
