apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scheduledscans.clusterscan-operator.cattle.io
spec:
  group: clusterscan-operator.cattle.io
  names:
    kind: ScheduledScan
    plural: scheduledscans
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cronSchedule:
              type: string
            retentionCount:
              type: integer
            scanProfileName:
              type: string
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  lastUpdateTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              nullable: true
              type: array
            enabled:
              type: boolean
            lastClusterScanName:
              type: string
            lastRunTimestamp:
              type: string
            observedGeneration:
              type: integer
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
